In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns

In [2]:
data=pd.read_csv('practice_data+(1).csv')
data.head()

,EmployeeID,gender,department,Days Present,Accuracy_of_Work,Meeting Project Deadlines,Task Completion Rates,Interpersonal Skills Rating,Decision-Making Skills Rating,Sales Revenue Generated,churned
0,1,Male,Sales,20,High,Yes,85,8,7,51638,No
1,2,Female,Marketing,22,Medium,Yes,90,7,6,97797,Yes
2,3,Male,Human Resources,25,High,No,80,9,8,95341,No
3,4,Male,Engineering,19,Low,Yes,75,6,5,91806,No
4,5,Female,Finance,23,Medium,Yes,85,7,7,64247,Yes

In [4]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
data['gender']=encoder.fit_transform(data['gender'])
data.head()

,EmployeeID,gender,department,Days Present,Accuracy_of_Work,Meeting Project Deadlines,Task Completion Rates,Interpersonal Skills Rating,Decision-Making Skills Rating,Sales Revenue Generated,churned
0,1,1,Sales,20,High,Yes,85,8,7,51638,No
1,2,0,Marketing,22,Medium,Yes,90,7,6,97797,Yes
2,3,1,Human Resources,25,High,No,80,9,8,95341,No
3,4,1,Engineering,19,Low,Yes,75,6,5,91806,No
4,5,0,Finance,23,Medium,Yes,85,7,7,64247,Yes